[package]
name = "ownership_basics"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ownership_in_rust"
path = "src/ownership_in_rust.rs"

[[bin]]
name = "references_and_borrowing"
path = "src/references_and_borrowing.rs"

[[bin]]
name = "slice_type"
path = "src/slice_type.rs"

[dependencies]
